from tkinter import*
from datetime import date
root = Tk()
root.geometry('700x500')
root.title('Age Calculator')
root.config(bg = 'blue')
def calculateAge():
    today = date.today()
    birthDate = date(int(e2.get()),int(e3.get()),int(e4.get()))
    age = today.year-birthDate.year-((today.month,today.day) < (birthDate.month,birthDate.day))
    l4 = Label(root,text = f"{nameValue.get()} your age is {age}",font =("Arial",16),fg = 'black',bg = "#F7DC6F")
    l4.grid(row=6,column= 1)
def destroy():
    root.destroy()
l = Label(root,text = 'Age Calulator App!',font = ("Arial",20),fg = "black",bg = "#F7DC6F")
l.grid(row=0,column = 0)
l1 = Label(root,text = "Name:",font =("Arial",16),fg = 'black',bg = "#F7DC6F")
l1.grid(row=1,column = 0,padx = 90)
l2 = Label(root,text = "Year",font =("Arial",16),fg = 'black',bg = "#F7DC6F")
l2.grid(row=2,column = 0)
l3 = Label(root,text = 'Month',font =("Arial",16),fg = 'black',bg = "#F7DC6F")
l3.grid(row = 3,column = 0)
l4 = Label(root,text = 'Day',font =("Arial",16),fg = 'black',bg = "#F7DC6F")
l4.grid(row = 4,column = 0)
nameValue = StringVar()
yearValue = StringVar()
monthValue = StringVar()
dayValue = StringVar()
e1=Entry(root,textvariable = nameValue,font =("Arial",16),fg = 'black',bg = "#F7DC6F")
e1.grid(row=1,column = 1,pady = 10)
e2=Entry(root,textvariable = yearValue,font =("Arial",16),fg = 'black',bg = "#F7DC6F")
e2.grid(row=2,column = 1,pady= 10)
e3=Entry(root,textvariable = monthValue,font =("Arial",16),fg = 'black',bg = "#F7DC6F")
e3.grid(row=3,column = 1,pady = 10)
e4=Entry(root,textvariable = dayValue,font =("Arial",16),fg = 'black',bg = "#F7DC6F")
e4.grid(row=4,column = 1,pady = 10)
btn = Button(root,text = "CalculatAge",command = calculateAge,font =("Arial",16),fg = 'black',bg = "#F7DC6F")
btn.grid(row=8,column = 1,pady = 10)
btn1 = Button(root,text = 'Exit',command = destroy,font =("Arial",16),fg = 'black',bg = "#F7DC6F")
btn1.grid(row=10,column = 1,pady = 10)
root.mainloop()
