from tkinter import*
root = Tk()
root.title('calculator')
root.geometry('700x900')
def click(event):
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(screen.get())

        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        screen.update()  
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
scvalue = StringVar()
scvalue.set("")
screen = Entry(root,text = scvalue,font = 'lucida 40 bold',fg = 'white',bg = 'blue')
screen.pack(fill = X,ipadx=20,pady = 10,padx=10)
f=Frame(root,bg='grey')
f.pack()
b=Button(f,text = '9',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=2,column=0)
b.bind("<Button-1>",click)
b=Button(f,text = '8',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=2,column=1)
b.bind("<Button-1>",click)
b=Button(f,text = '7',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=2,column = 2)
b.bind("<Button-1>",click)
b=Button(f,text = '6',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=3,column = 0)
b.bind("<Button-1>",click)
b=Button(f,text = '5',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=3,column=1)
b.bind("<Button-1>",click)
b=Button(f,text = '4',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=3,column=2)
b.bind("<Button-1>",click)
b=Button(f,text = '3',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=4,column=0)
b.bind("<Button-1>",click)
b=Button(f,text = '2',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=4,column=1)
b.bind("<Button-1>",click)
b=Button(f,text = '1',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=4,column=2)
b.bind("<Button-1>",click)
b=Button(f,text = '0',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=5,column=0)
b.bind("<Button-1>",click)
b=Button(f,text = '-',padx = 35,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=5,column = 1)
b.bind("<Button-1>",click)
b=Button(f,text = '+',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=5,column=2)
b.bind("<Button-1>",click)
b=Button(f,text = '*',padx = 35,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=6,column=0)
b.bind("<Button-1>",click)
b=Button(f,text = '/',padx = 35,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=6,column=1)
b.bind("<Button-1>",click)
b=Button(f,text = '=',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=6,column=2)
b.bind("<Button-1>",click)
b=Button(f,text = '%',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=7,column=0)
b.bind("<Button-1>",click)
b=Button(f,text = 'C',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=7, column=1)
b.bind("<Button-1>",click)
b=Button(f,text = '7',padx = 30,pady = 15,font = 'lucida 35 bold',fg = 'white',bg = 'green')
b.grid(row=7, column=2)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()

