from tkinter import*
root = Tk()
root.title('Registration form')
root.config(bg = 'blue')
def clicked():
    print(en1.get())
    print(en2.get())
print('your form submit successfully!')
lb = Label(root,text = 'Registration form',bg = 'blue',font = ('Times','35','bold'))
lb.grid(row=0,column = 0)
lb1 = Label(root,text = 'FullName:',width = 20,font = ('bold',15))
lb1.grid(row=2,column = 0)
en1 = Entry(root,font = ('bold',10))
en1.grid(row=2,column = 1)
lb2 = Label(root,text = 'Email:',font = ('bold',15))
lb2.grid(row=3,column = 0)
en2 = Entry(root,font = ('bold',10))
en2.grid(row=3,column = 1)
lb3 =Label(root,text = 'Gender:',font = ('bold',15))
lb3.grid(row = 4,column = 0)
var = IntVar()
a = Radiobutton(root,text = 'male',padx = 15,variable = var,font = ('bold',10),value = 1).grid(row=4,column = 1)
b = Radiobutton(root,text = 'female',padx = 15,variable = var,font = ('bold',10),value = 2).grid(row=4,column = 2)
lb4 = Label(root,text = 'Country:',width = 20,font = ('bold',15))
lb4.grid(row=5,column = 0)
options = ["CANADA","US","INDIA","NEPAL","AUSTRALIA","BANGLADESH","BHUTAN"]
c = StringVar()
c.set('select your country')
droplist = OptionMenu(root,c,*options)
droplist.config(width = 15)
droplist.grid(row=5,column = 1)
lb5 = Label(root,text = 'Programming:',width = 20,font = ('bold',15))
lb5.grid(row=6,column = 0)
var1 = IntVar()
c1 = Checkbutton(root,text = 'python',variable = var1)
c1.grid(row=6,column=1)
var2 = IntVar()
c2 = Checkbutton(root,text = 'C',variable = var2)
c2.grid(row=6,column = 2)
btn = Button(root,text = 'Submit',font = ('bold',15),bg = 'black',fg = 'white',command = clicked)
btn.place(x=300,y =250)
root.mainloop()
